In [1]:
print("kello")

kello


In [2]:
#Let's start Numpy
import numpy as np
a = np.arange(1,12,2)
a
a.reshape(3,2)


array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [51]:
b=np.array([[3,4,5],
           [6,7,9],
           [10,11,13]])
b
# print(b[0:1,1:2])# it prints a part of 2d-array like:[0][1]=4
# print(b[b<7])# this will print all values less then 7 in 1d array
# # print(np.sum(b,axis=0))# row sum col-wise i.e [3, 4, 5] + [6,7,9]+[10,11,13]=[3+6+10,4+7+11,5+9+13]=[19, 22, 27]
# print(np.sum(b,axis=1))# col sum row-wise i.e. [3+4+5 ,6+7+9 , 10+11+13] = [12 ,22 ,34] 

array([[ 3,  4,  5],
       [ 6,  7,  9],
       [10, 11, 13]])

In [ ]:
x = np.arange(10)
print(x)
y = np.arange(10,19).reshape(3,3)
print(y)
# print(y[1:2,:])# [row_start :row_end-1, col_start:col_end-1]
print("1",y[0:,:])# this will print whole 3x3 2d array
print("2",y[1:, :])#This will print 2x3 -> [1:,:] means 2nd and 3rd row will print
print("3",y[2:,:])# this will print 1x3->[2:,:] means 3rd row will print
print("4",y[:,0:])# print("1",y[0:,:]) 3x3 matrix will be printed
print("5",y[:,1:])# print 2nd and 3rd col 3x2 -> [:,1:] 2nd and 3rd col will be print
print("6",y[:,2:])# print 3rd col only
# print(y[:,:])

[0 1 2 3 4 5 6 7 8 9]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
1 [[10 11 12]
 [13 14 15]
 [16 17 18]]
2 [[13 14 15]
 [16 17 18]]
3 [[16 17 18]]
4 [[10 11 12]
 [13 14 15]
 [16 17 18]]
5 [[11 12]
 [14 15]
 [17 18]]
6 [[12]
 [15]
 [18]]


In [67]:
y = np.arange(10, 19).reshape(3, 3)
print(y)
# print("1", y[0:1, 0:1])
# print("2",y[0:1, 1:2])
# print("3",y[0:1,2:3])
# print("4",y[1:2,0:1])
# print("5",y[1:2,1:2])
# print("6",y[1:2,2:3])
# print("7",y[2:3,0:1])
# print("8",y[2:3,1:2])
# print("9",y[2:3,2:3])
# print("10",y[0:2,0:2])
# print("11",y[0:2,1:3])
# print("12",y[1:3,0:2])
# print("13",y[1:3,1:3])
# print("14",y[0:1,2:])
# print("15",y[0:1,1:3])


[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [21]:
import numpy as np
x =np.arange(30,50).reshape(4,5)
print(x)

arr = np.zeros((3, 3))
arr

[[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.ones((2,3))#This prints only 1's
arr



array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr1 = np.identity(3)# identity matrix
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
X = np.arange(5,16,2)# prints 5 to 16 no having gap of 2
X



array([ 5,  7,  9, 11, 13, 15])

In [37]:
Y = np.linspace(10,20,10) #this will print 10 no's between 10 to 20  (i.e. 10,11.11111,12.22222.......etc)
Y

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
temp = X.copy()# array element of X copied to temp
temp

array([ 5,  7,  9, 11, 13, 15])