In [1]:
print("kello")

kello


In [2]:
#Let's start Numpy
import numpy as np
a = np.arange(1,12,2)
a
a.reshape(3,2)


array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [51]:
b=np.array([[3,4,5],
           [6,7,9],
           [10,11,13]])
b
# print(b[0:1,1:2])# it prints a part of 2d-array like:[0][1]=4
# print(b[b<7])# this will print all values less then 7 in 1d array
# # print(np.sum(b,axis=0))# row sum col-wise i.e [3, 4, 5] + [6,7,9]+[10,11,13]=[3+6+10,4+7+11,5+9+13]=[19, 22, 27]
# print(np.sum(b,axis=1))# col sum row-wise i.e. [3+4+5 ,6+7+9 , 10+11+13] = [12 ,22 ,34] 

array([[ 3,  4,  5],
       [ 6,  7,  9],
       [10, 11, 13]])

In [ ]:
x = np.arange(10)
print(x)
y = np.arange(10,19).reshape(3,3)
print(y)
# print(y[1:2,:])# [row_start :row_end-1, col_start:col_end-1]
print("1",y[0:,:])# this will print whole 3x3 2d array
print("2",y[1:, :])#This will print 2x3 -> [1:,:] means 2nd and 3rd row will print
print("3",y[2:,:])# this will print 1x3->[2:,:] means 3rd row will print
print("4",y[:,0:])# print("1",y[0:,:]) 3x3 matrix will be printed
print("5",y[:,1:])# print 2nd and 3rd col 3x2 -> [:,1:] 2nd and 3rd col will be print
print("6",y[:,2:])# print 3rd col only
# print(y[:,:])

[0 1 2 3 4 5 6 7 8 9]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
1 [[10 11 12]
 [13 14 15]
 [16 17 18]]
2 [[13 14 15]
 [16 17 18]]
3 [[16 17 18]]
4 [[10 11 12]
 [13 14 15]
 [16 17 18]]
5 [[11 12]
 [14 15]
 [17 18]]
6 [[12]
 [15]
 [18]]


In [67]:
y = np.arange(10, 19).reshape(3, 3)
print(y)
# print("1", y[0:1, 0:1])
# print("2",y[0:1, 1:2])
# print("3",y[0:1,2:3])
# print("4",y[1:2,0:1])
# print("5",y[1:2,1:2])
# print("6",y[1:2,2:3])
# print("7",y[2:3,0:1])
# print("8",y[2:3,1:2])
# print("9",y[2:3,2:3])
# print("10",y[0:2,0:2])
# print("11",y[0:2,1:3])
# print("12",y[1:3,0:2])
# print("13",y[1:3,1:3])
# print("14",y[0:1,2:])
# print("15",y[0:1,1:3])


[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [21]:
import numpy as np
x =np.arange(30,50).reshape(4,5)
print(x)

arr = np.zeros((3, 3))
arr

[[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
arr = np.ones((2,3))#This prints only 1's
arr



array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
arr1 = np.identity(3)# identity matrix
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
X = np.arange(5,16,2)# prints 5 to 16 no having gap of 2
X



array([ 5,  7,  9, 11, 13, 15])

In [37]:
Y = np.linspace(10,20,10) #this will print 10 no's between 10 to 20  (i.e. 10,11.11111,12.22222.......etc)
Y

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [38]:
temp = X.copy()# array element of X copied to temp
temp

array([ 5,  7,  9, 11, 13, 15])

In [58]:
# Shape
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr3.shape #this operation tells the shape of n-dim array
arr3.size#it tells no of elements the arr3 have
# arr3[0, 0, 0] = 10  # equivalent to arr3.itemset((0, 0, 0), 10)
# arr3.itemsize --> giving same answer as arr3.size
arr3.dtype # this tell data type
arr3.astype('float') #.astype() change data type


dtype('int64')

In [74]:
a = list(range(22)) #list is also an array but it can carry elements of all data type, that's why it is slower then numpy array
a
arr = np.arange(21)# Numpy arrays are homogenious can contain/carry only same data type means int,float,.....etc
arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [79]:
import sys
print(sys.getsizeof(19)*len(a))#19 lies in range of list 0 to 21,size of 19 in byters = 19*28 = 532
print(arr.itemsize*arr.size)# size of one item in arr = 4 bytes then total size of arr = 21*4 = 84 bytes
# That's why numpy arrays takes less memory then lists

616
168


In [ ]:
import time
t1 = np.arange(100)

t2 = np.arange(100,200)

start_time = time.time()
print(start_time)
# t = list(t1) + list(t2)# this perform python concatenation
# t = t1+t2 # this performs element wise addition
np.concatenate([t1,t2])# use in numpy and its faster then list()
print(time.time()-start_time)

1788864757.451827
0.003997087478637695


In [99]:
s1 = np.arange(100000)
# print(np.sum(s1))
s2 = np.arange(100000,200000)
# print(np.sum(s2))
T = time.time()
s = s1+s2
print(np.sum(s))
print(time.time()-T)


19999900000
0.0019979476928710938


In [ ]:
s1 = np.arange(100000000)
# print(np.sum(s1))
s2 = np.arange(100000000,200000000)
# print(np.sum(s2))
T = time.time()# it records current time in seconds just before the calculation starts
s = s1+s2
print(np.sum(s))
print(time.time()-T)# this show the time difference or time taken by program to execute properly


19999999900000000
37.60596323013306


In [ ]:
# Scenario: A stock trading bot must process 1 million price ticks in under 0.5 seconds to execute a buy/sell decision 
# before the market moves — you use time.time() to benchmark your NumPy calculations and optimize if it's too slow.
# Below is the typical example of how shares are buy/sell
import numpy as np
import time

# Simulate 1 million price ticks/fake price
prices = np.random.rand(1_000_000) * 100

start = time.time()# it records current time in seconds just before the calculation starts
moving_avg = np.mean(prices[-100:])  # Last 100 ticks/prices
decision = "BUY" if moving_avg < 50 else "SELL"
elapsed = time.time() - start

print(f"Decision: {decision}, Time: {elapsed:.5f}s")
if elapsed > 0.5:
    print("Too slow — optimize or upgrade hardware")

Decision: SELL, Time: 0.01734s


In [114]:
# Indexing , Slicing , Iteration
a = np.arange(24)
a
a.reshape(6,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [137]:
# print(a[:])# this converts/print all numbers into 1d array

b = np.arange(6,21,2)
b
print(b)
print(b[3:7])# slicing
print(b[6])# indexing --> fetch element at index:6 = 18
print(b[5:6])
print(b[-4:-1])# reverse order slicing

[ 6  8 10 12 14 16 18 20]
[12 14 16 18]
18
[16]
[14 16 18]


In [149]:
#Iteration
# for i in b:
#     print(i)
A = np.arange(5,14).reshape(3,3)
A
for i in A:
    print(i)
print(A[A%2==0])
print(A[A%2!=0])
print(A[A>10])

[5 6 7]
[ 8  9 10]
[11 12 13]
[ 6  8 10 12]
[ 5  7  9 11 13]
[11 12 13]


In [150]:
# This iterate all the elements of a 2D array in vertical manner
for i in np.nditer(A):
    print(i)

5
6
7
8
9
10
11
12
13


In [168]:
#Basic Operations
p = np.floor(np.random.random(5) * 10 + 1)
q = np.floor(np.random.random(5) * 10 + 1)
print(p)
print(q)
print("sum:",p+q)
print("mul:",p*q)
print("div:",p//q)
print("rem:",p%q)
p>20


[1. 9. 5. 2. 5.]
[3. 6. 8. 7. 2.]
sum: [ 4. 15. 13.  9.  7.]
mul: [ 3. 54. 40. 14. 10.]
div: [0. 1. 0. 0. 2.]
rem: [1. 3. 5. 2. 1.]


array([False, False, False, False, False])

In [170]:
#Matrix multiplication dot product
arr1 = np.arange(6).reshape(2,3)# 2x3
arr2 =np.arange(7,13).reshape(3,2)# 3x2
print(arr1)
print(arr2)
arr1.dot(arr2)

[[0 1 2]
 [3 4 5]]
[[ 7  8]
 [ 9 10]
 [11 12]]


array([[ 31,  34],
       [112, 124]])

In [182]:
arr3 = np.arange(9).reshape(3, 3)
arr4 = np.arange(10, 19).reshape(3, 3)
print(arr3)
print(arr4)
arr3.dot(arr4)
print(arr3.max())
print(arr3.min())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
8
0


In [186]:
arr3.min(axis=0)#Display row with min values
arr3.max(axis=0)#Display col with max values
arr3.min(axis =1)
arr3.max(axis=1)

array([2, 5, 8])

In [ ]:
arr4.sum()#It sum() all the elements in a 2d array
arr4.sum(axis=1)# this sum col elements row-wise like(a11+a12+a13)= 10+11+12 = 33
arr4.sum(axis=0)# this sum row elements col-wise like(c11+c21+c31)= 10+13+16 = 39

array([39, 42, 45])

In [ ]:
# some mathematical and statistical operations
print(arr3.mean())
print(arr4.mean())
np.median(arr4)
np.std(arr4)

4.0
14.0


np.float64(2.581988897471611)

In [ ]:
#sine function
np.sin(arr3)# Here input values of arr3 treated as angles in radians and give output as sine value

#exponent
np.exp(arr3) # for each element of array np.exp() calculates exponent


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])